Repository SOLPLY/SOLPLY-SERVER, pull requests merged in 2025-07, with the labels that each got.

#11 [CHORE] Swagger 설정
  src/main/java/org/sopt/solply_server/global/config/SwaggerConfig.java
Labels: CHORE

#29 [CHORE] HttpRequestMethodNotSupportedException 핸들러 수정
  .gitignore
  docker/docker-compose.yml
  src/main/java/org/sopt/solply_server/global/handler/GlobalExceptionHandler.java
Labels: CHORE

#31 [FEAT] s3 연결 세팅, 읽기용 presignedurl 발급, 공개 이미지 접근 url 발급
  src/main/java/org/sopt/solply_server/global/config/AwsConfig.java
  src/main/java/org/sopt/solply_server/global/util/InputValidator.java
  src/main/java/org/sopt/solply_server/global/util/s3/ImageUrlProvider.java
  src/main/java/org/sopt/solply_server/global/util/s3/PresignedUrlProvider.java
Labels: FEAT

#33 [CHORE] Redis 기본 세팅, RedisInsight(docker-compose.yml) 세팅
  src/main/java/org/sopt/solply_server/global/cache/CacheService.java
  src/main/java/org/sopt/solply_server/global/cache/RedisCacheService.java
  src/main/java/org/sopt/solply_server/global/config/RedisConfig.java
  src/main/java/org/sopt/solply_server/global/exception/ErrorCode.java
  src/main/java/org/sopt/solply_server/global/util/s3/PresignedUrlProvider.java
Labels: CHORE

#37 [FEAT] 카카오 소셜 로그인
  src/main/java/org/sopt/solply_server/SolplyServerApplication.java
  src/main/java/org/sopt/solply_server/domain/auth/constant/SocialPlatform.java
  src/main/java/org/sopt/solply_server/domain/auth/controller/AuthController.java
  src/main/java/org/sopt/solply_server/domain/auth/dto/TokenDto.java
  src/main/java/org/sopt/solply_server/domain/auth/dto/request/SocialLoginRequest.java
  src/main/java/org/sopt/solply_server/domain/auth/dto/response/RefreshResponse.java
  src/main/java/org/sopt/solply_server/domain/auth/dto/response/SocialLoginResponse.java
  src/main/java/org/sopt/solply_server/domain/auth/repository/RefreshTokenRepository.java
  src/main/java/org/sopt/solply_server/domain/auth/service/AuthService.java
  src/main/java/org/sopt/solply_server/domain/auth/service/OAuthService.java
  src/main/java/org/sopt/solply_server/domain/auth/service/OAuthServiceProvider.java
  src/main/java/org/sopt/solply_server/domain/auth/service/oauth/KakaoOAuthServiceImpl.java
  src/main/java/org/sopt/solply_server/domain/user/entity/SocialUserInfo.java
  src/main/java/org/sopt/solply_server/domain/user/entity/User.java
  src/main/java/org/sopt/solply_server/domain/user/repository/SocialUserInfoRepository.java
  src/main/java/org/sopt/solply_server/domain/user/repository/UserRepository.java
  src/main/java/org/sopt/solply_server/domain/user/service/SocialUserService.java
  src/main/java/org/sopt/solply_server/domain/user/service/UserService.java
  src/main/java/org/sopt/solply_server/global/annotation/CurrentUserId.java
  src/main/java/org/sopt/solply_server/global/common/SuccessCode.java
  src/main/java/org/sopt/solply_server/global/config/FeignConfig.java
  src/main/java/org/sopt/solply_server/global/config/RedisConfig.java
  src/main/java/org/sopt/solply_server/global/config/WebConfig.java
  src/main/java/org/sopt/solply_server/global/dto/CustomApiResponse.java
  src/main/java/org/sopt/solply_server/global/exception/ErrorCode.java
  src/main/java/org/sopt/solply_server/global/feign/oauth/kakao/KakaoServerClient.java
  src/main/java/org/sopt/solply_server/global/feign/oauth/kakao/dto/KakaoSocialUserProfile.java
  src/main/java/org/sopt/solply_server/global/handler/GlobalExceptionHandler.java
  src/main/java/org/sopt/solply_server/global/http/SocialPlatformRequestConverter.java
  src/main/java/org/sopt/solply_server/global/jwt/JwtAuthenticationFilter.java
  src/main/java/org/sopt/solply_server/global/jwt/JwtTokenProvider.java
  src/main/java/org/sopt/solply_server/global/jwt/JwtTokenResolver.java
  src/main/java/org/sopt/solply_server/global/jwt/dto/TokenCollectionDto.java
  src/main/java/org/sopt/solply_server/global/security/PrincipalDetails.java
  src/main/java/org/sopt/solply_server/global/security/PrincipalDetailsService.java
Labels: FEAT

#41 [FEAT] 테스트 유저 가입 및 탈퇴 API 구현
  src/main/java/org/sopt/solply_server/domain/test/controller/TestController.java
  src/main/java/org/sopt/solply_server/domain/test/dto/response/TestLoginResponse.java
  src/main/java/org/sopt/solply_server/domain/test/service/TestService.java
  src/main/java/org/sopt/solply_server/global/exception/ErrorCode.java
Labels: FEAT

#43 [FEAT] 엔티티 세팅, 필요한 Enum 세팅
  src/main/java/org/sopt/solply_server/domain/auth/controller/AuthController.java
  src/main/java/org/sopt/solply_server/domain/auth/entity/SocialPlatform.java
  src/main/java/org/sopt/solply_server/domain/auth/service/AuthService.java
  src/main/java/org/sopt/solply_server/domain/auth/service/OAuthService.java
  src/main/java/org/sopt/solply_server/domain/auth/service/OAuthServiceProvider.java
  src/main/java/org/sopt/solply_server/domain/auth/service/oauth/KakaoOAuthServiceImpl.java
  src/main/java/org/sopt/solply_server/domain/course/entity/Course.java
  src/main/java/org/sopt/solply_server/domain/course/entity/CoursePlace.java
  src/main/java/org/sopt/solply_server/domain/place/entity/Place.java
  src/main/java/org/sopt/solply_server/domain/place/entity/PlaceBookmark.java
  src/main/java/org/sopt/solply_server/domain/place/entity/PlaceImageInfo.java
  src/main/java/org/sopt/solply_server/domain/place/entity/SnsPlatform.java
  src/main/java/org/sopt/solply_server/domain/tag/entity/Tag.java
  src/main/java/org/sopt/solply_server/domain/tag/entity/TagType.java
  src/main/java/org/sopt/solply_server/domain/town/entity/Town.java
  src/main/java/org/sopt/solply_server/domain/user/entity/SocialUserInfo.java
  src/main/java/org/sopt/solply_server/domain/user/entity/User.java
  src/main/java/org/sopt/solply_server/domain/user/entity/UserInterestTown.java
  src/main/java/org/sopt/solply_server/domain/user/service/SocialUserService.java
  src/main/java/org/sopt/solply_server/domain/user/service/UserService.java
  src/main/java/org/sopt/solply_server/global/http/SocialPlatformRequestConverter.java
Labels: FEAT

#50 [FEAT] 장소 세부 정보 단일 조회 API 구현, 더미데이터 sql 스크립트, imageurl 발급(수정)
  .github/workflows/CD.yml
  build.gradle
  src/main/java/org/sopt/solply_server/domain/place/controller/PlaceController.java
  src/main/java/org/sopt/solply_server/domain/place/dto/PlaceImageInfoDto.java
  src/main/java/org/sopt/solply_server/domain/place/dto/SnsLinkDto.java
  src/main/java/org/sopt/solply_server/domain/place/dto/response/PlaceAllGetResponse.java
  src/main/java/org/sopt/solply_server/domain/place/entity/Place.java
  src/main/java/org/sopt/solply_server/domain/place/entity/PlaceImageInfo.java
  src/main/java/org/sopt/solply_server/domain/place/entity/PlaceTag.java
  src/main/java/org/sopt/solply_server/domain/place/repository/PlaceBookmarkRepository.java
  src/main/java/org/sopt/solply_server/domain/place/repository/PlaceRepository.java
  src/main/java/org/sopt/solply_server/domain/place/repository/PlaceTagRepository.java
  src/main/java/org/sopt/solply_server/domain/place/service/PlaceService.java
  src/main/java/org/sopt/solply_server/domain/tag/entity/Tag.java
  src/main/java/org/sopt/solply_server/domain/tag/entity/TagName.java
  src/main/java/org/sopt/solply_server/domain/town/entity/Town.java
  src/main/java/org/sopt/solply_server/global/exception/EntityNotFoundException.java
  src/main/java/org/sopt/solply_server/global/exception/ErrorCode.java
  src/main/java/org/sopt/solply_server/global/util/InputValidator.java
  src/main/java/org/sopt/solply_server/global/util/s3/ImageUrlProvider.java
  src/main/resources/db/init/01_insert_towns.sql
  src/main/resources/db/init/02_insert_tags.sql
  src/main/resources/db/init/03_insert_places.sql
  src/main/resources/db/init/04_insert_place_images.sql
  src/main/resources/db/init/05_insert_social_links.sql
  src/main/resources/db/init/06_insert_place_tag.sql
Labels: FEAT

#54 [FEAT] 전체동네 리스트 API구현
  .gitignore
  src/main/java/org/sopt/solply_server/domain/town/controller/TownController.java
  src/main/java/org/sopt/solply_server/domain/town/dto/TownDto.java
  src/main/java/org/sopt/solply_server/domain/town/dto/TownResponse.java
  src/main/java/org/sopt/solply_server/domain/town/entity/Town.java
  src/main/java/org/sopt/solply_server/domain/town/repository/TownRepository.java
  src/main/java/org/sopt/solply_server/domain/town/service/TownService.java
Labels: FEAT

#51 [FEAT] 회원정보 업데이트 API 구현
  build.gradle
  src/main/java/org/sopt/solply_server/domain/town/service/TownService.java
  src/main/java/org/sopt/solply_server/domain/user/controller/UserController.java
  src/main/java/org/sopt/solply_server/domain/user/dto/request/UserUpdateRequest.java
  src/main/java/org/sopt/solply_server/domain/user/dto/response/UserUpdateResponse.java
  src/main/java/org/sopt/solply_server/domain/user/entity/User.java
  src/main/java/org/sopt/solply_server/domain/user/entity/UserInterestTown.java
  src/main/java/org/sopt/solply_server/domain/user/entity/UserPersona.java
  src/main/java/org/sopt/solply_server/domain/user/repository/UserInterestTownRepository.java
  src/main/java/org/sopt/solply_server/domain/user/service/OnboardingService.java
  src/main/java/org/sopt/solply_server/domain/user/service/UserInterestTownService.java
  src/main/java/org/sopt/solply_server/domain/user/service/UserService.java
  src/main/java/org/sopt/solply_server/domain/user/service/UserValidator.java
  src/main/java/org/sopt/solply_server/global/config/RetryConfig.java
  src/main/java/org/sopt/solply_server/global/exception/ErrorCode.java
Labels: FEAT

#55 [FEAT] 장소 필터링 API 구현
  docker/initdb/01_insert_towns.sql
  docker/initdb/02_insert_tags.sql
  docker/initdb/03_insert_places.sql
  docker/initdb/04_insert_place_images.sql
  docker/initdb/05_insert_social_links.sql
  docker/initdb/06_insert_place_tag.sql
  src/main/java/org/sopt/solply_server/domain/place/controller/PlaceController.java
  src/main/java/org/sopt/solply_server/domain/place/dto/PlaceThumbnailDto.java
  src/main/java/org/sopt/solply_server/domain/place/dto/request/PlaceFilterGetRequest.java
  src/main/java/org/sopt/solply_server/domain/place/dto/response/PlaceFilterGetResponse.java
  src/main/java/org/sopt/solply_server/domain/place/entity/Place.java
  src/main/java/org/sopt/solply_server/domain/place/entity/PlaceTag.java
  src/main/java/org/sopt/solply_server/domain/place/repository/PlaceRepository.java
  src/main/java/org/sopt/solply_server/domain/place/service/PlaceService.java
  src/main/java/org/sopt/solply_server/domain/tag/entity/Tag.java
  src/main/java/org/sopt/solply_server/domain/tag/repository/TagRepository.java
  src/main/java/org/sopt/solply_server/domain/tag/service/TagService.java
  src/main/java/org/sopt/solply_server/domain/tag/util/TagValidator.java
  src/main/java/org/sopt/solply_server/domain/town/service/TownService.java
  src/main/java/org/sopt/solply_server/domain/town/util/TownValidator.java
  src/main/java/org/sopt/solply_server/global/exception/ErrorCode.java
  src/main/java/org/sopt/solply_server/global/util/InputValidator.java
  src/main/java/org/sopt/solply_server/global/util/s3/ImageUrlProvider.java
  src/main/java/org/sopt/solply_server/global/util/s3/PresignedUrlProvider.java
Labels: FEAT

#56 [FEAT] 회원 정보 조회 API 구현
  src/main/java/org/sopt/solply_server/domain/user/controller/UserController.java
  src/main/java/org/sopt/solply_server/domain/user/dto/SelectedTownDto.java
  src/main/java/org/sopt/solply_server/domain/user/dto/response/UserProfileGetResponse.java
  src/main/java/org/sopt/solply_server/domain/user/repository/UserInterestTownRepository.java
  src/main/java/org/sopt/solply_server/domain/user/service/UserService.java
Labels: FEAT

#61 #57 fix: docker-compose.yml 배포 파이프라인 수정
  .github/workflows/CD.yml
Labels: BUG

#62 [FIX] docker-compose.yml 배포 파이프라인 수정
  .github/workflows/CD.yml
Labels: BUG

#66 [FEAT] 북마크 저장/삭제 API
  src/main/java/org/sopt/solply_server/domain/place/controller/PlaceController.java
  src/main/java/org/sopt/solply_server/domain/place/dto/BookmarkRedisDto.java
  src/main/java/org/sopt/solply_server/domain/place/entity/PlaceBookmark.java
  src/main/java/org/sopt/solply_server/domain/place/repository/PlaceBookmarkRepository.java
  src/main/java/org/sopt/solply_server/domain/place/service/PlaceBookmarkService.java
  src/main/java/org/sopt/solply_server/domain/place/service/cache/BookmarkFlushScheduler.java
  src/main/java/org/sopt/solply_server/domain/place/service/cache/BookmarkRedisDataProcessor.java
  src/main/java/org/sopt/solply_server/global/cache/CacheService.java
  src/main/java/org/sopt/solply_server/global/cache/FlushResult.java
  src/main/java/org/sopt/solply_server/global/cache/RedisCacheService.java
  src/main/java/org/sopt/solply_server/global/cache/RedisDataProcessor.java
  src/main/java/org/sopt/solply_server/global/cache/RedisFlushScheduler.java
  src/main/java/org/sopt/solply_server/global/config/RedisConfig.java
  src/main/java/org/sopt/solply_server/global/exception/ErrorCode.java
  src/main/java/org/sopt/solply_server/global/exception/RedisFlushException.java
  src/main/java/org/sopt/solply_server/global/exception/RedisSchedulerException.java
  src/main/java/org/sopt/solply_server/global/handler/GlobalExceptionHandler.java
Labels: FEAT

#70 [FEAT] 페르소나 리스트조회 API구현
  src/main/java/org/sopt/solply_server/domain/user/controller/UserOnboardingController.java
  src/main/java/org/sopt/solply_server/domain/user/dto/UserPersonaDto.java
  src/main/java/org/sopt/solply_server/domain/user/dto/response/UserPersonaListGetResponse.java
  src/main/java/org/sopt/solply_server/domain/user/service/UserOnboardingService.java
Labels: FEAT

#71 [FEAT] 추천 코스 조회 API 구현
  src/main/java/org/sopt/solply_server/domain/course/controller/CourseController.java
  src/main/java/org/sopt/solply_server/domain/course/dto/CourseRecommendDto.java
  src/main/java/org/sopt/solply_server/domain/course/dto/response/CourseRecommendGetResponse.java
  src/main/java/org/sopt/solply_server/domain/course/repository/CourseRepository.java
  src/main/java/org/sopt/solply_server/domain/course/service/CourseService.java
Labels: FEAT

#73 [FEAT] 동네 썸네일 조회 API
  src/main/java/org/sopt/solply_server/domain/place/controller/PlaceController.java
  src/main/java/org/sopt/solply_server/domain/place/dto/FolderThumbnailDto.java
  src/main/java/org/sopt/solply_server/domain/place/dto/response/PlaceThumbnailListGetResponse.java
  src/main/java/org/sopt/solply_server/domain/place/entity/PlaceBookmark.java
  src/main/java/org/sopt/solply_server/domain/place/repository/PlaceBookmarkRepository.java
  src/main/java/org/sopt/solply_server/domain/place/repository/PlaceRepository.java
  src/main/java/org/sopt/solply_server/domain/place/service/PlaceBookmarkService.java
  src/main/java/org/sopt/solply_server/domain/place/service/PlaceService.java
  src/main/java/org/sopt/solply_server/domain/place/service/cache/BookmarkFlushScheduler.java
  src/main/java/org/sopt/solply_server/domain/place/service/cache/BookmarkRedisDataManager.java
  src/main/java/org/sopt/solply_server/global/cache/CachePrefix.java
  src/main/java/org/sopt/solply_server/global/cache/RedisDataManager.java
  src/main/java/org/sopt/solply_server/global/cache/RedisKeyGenerator.java
  src/main/java/org/sopt/solply_server/global/entity/BaseTimeEntity.java
Labels: FEAT

#74 [FEAT] 코스 북마크 저장/삭제 API 구현
  src/main/java/org/sopt/solply_server/domain/course/controller/CourseController.java
  src/main/java/org/sopt/solply_server/domain/course/dto/CourseBookmarkRedisDto.java
  src/main/java/org/sopt/solply_server/domain/course/entity/CourseBookmark.java
  src/main/java/org/sopt/solply_server/domain/course/repository/CourseBookmarkRepository.java
  src/main/java/org/sopt/solply_server/domain/course/service/CourseBookmarkService.java
  src/main/java/org/sopt/solply_server/domain/course/service/CourseService.java
  src/main/java/org/sopt/solply_server/domain/course/service/cache/CourseBookmarkRedisDataManager.java
  src/main/java/org/sopt/solply_server/domain/place/service/PlaceBookmarkService.java
  src/main/java/org/sopt/solply_server/domain/place/service/cache/BookmarkRedisDataManager.java
  src/main/java/org/sopt/solply_server/global/cache/CachePrefix.java
  src/main/java/org/sopt/solply_server/global/cache/RedisKeyGenerator.java
  src/main/java/org/sopt/solply_server/global/exception/ErrorCode.java
Labels: FEAT

#75 [FEAT] 특정 동네에 대한 장소 리스트 조회 API
  src/main/java/org/sopt/solply_server/domain/place/controller/PlaceController.java
  src/main/java/org/sopt/solply_server/domain/place/dto/request/PlaceFilterGetRequest.java
  src/main/java/org/sopt/solply_server/domain/place/dto/response/PlaceFolderThumbnailListGetResponse.java
  src/main/java/org/sopt/solply_server/domain/place/dto/response/PlaceThumbnailListGetResponse.java
  src/main/java/org/sopt/solply_server/domain/place/entity/PlaceBookmark.java
  src/main/java/org/sopt/solply_server/domain/place/repository/PlaceRepository.java
  src/main/java/org/sopt/solply_server/domain/place/service/PlaceBookmarkService.java
  src/main/java/org/sopt/solply_server/domain/place/service/PlaceService.java
  src/main/java/org/sopt/solply_server/domain/place/service/cache/BookmarkFlushScheduler.java
  src/main/java/org/sopt/solply_server/domain/place/service/cache/BookmarkRedisDataManager.java
Labels: FEAT

#80 [FEAT] 코스 북마크 동네 폴더링 프리뷰 조회 API 구현
  src/main/java/org/sopt/solply_server/domain/course/controller/CourseController.java
  src/main/java/org/sopt/solply_server/domain/course/dto/CourseFolderDto.java
  src/main/java/org/sopt/solply_server/domain/course/dto/CoursePreviewDto.java
  src/main/java/org/sopt/solply_server/domain/course/dto/response/CourseFolderPreviewListGetResponse.java
  src/main/java/org/sopt/solply_server/domain/course/dto/response/CourseRecommendGetResponse.java
  src/main/java/org/sopt/solply_server/domain/course/mapper/CourseMapper.java
  src/main/java/org/sopt/solply_server/domain/course/repository/CourseRepository.java
  src/main/java/org/sopt/solply_server/domain/course/service/CourseService.java
  src/main/java/org/sopt/solply_server/domain/course/service/cache/CourseBookmarkRedisDataManager.java
  src/main/java/org/sopt/solply_server/domain/place/service/PlaceService.java
Labels: FEAT

#89 [FIX] script validation 문제 수정
  src/main/java/org/sopt/solply_server/SolplyServerApplication.java
  src/main/resources/db/migration/V1__create_initial_tables.sql
Labels: CHORE

#87 [FIX] 동네리스트 전체조회 오류수정
  src/main/java/org/sopt/solply_server/domain/town/controller/TownController.java
  src/main/java/org/sopt/solply_server/domain/town/dto/TownResponse.java
  src/main/java/org/sopt/solply_server/domain/town/dto/response/TownAllGetResponse.java
  src/main/java/org/sopt/solply_server/domain/town/repository/TownRepository.java
  src/main/java/org/sopt/solply_server/domain/town/service/TownService.java
  src/main/java/org/sopt/solply_server/domain/user/service/UserOnboardingService.java
Labels: BUG

#88 [FEAT] 코스 생성 API 구현
  src/main/java/org/sopt/solply_server/SolplyServerApplication.java
  src/main/java/org/sopt/solply_server/domain/course/controller/CourseController.java
  src/main/java/org/sopt/solply_server/domain/course/dto/request/CourseCreateRequest.java
  src/main/java/org/sopt/solply_server/domain/course/dto/response/CourseCreateResponse.java
  src/main/java/org/sopt/solply_server/domain/course/entity/Course.java
  src/main/java/org/sopt/solply_server/domain/course/entity/CoursePlace.java
  src/main/java/org/sopt/solply_server/domain/course/repository/CourseRepository.java
  src/main/java/org/sopt/solply_server/domain/course/service/CourseBookmarkService.java
  src/main/java/org/sopt/solply_server/domain/course/service/CourseService.java
  src/main/java/org/sopt/solply_server/domain/course/util/CourseNameGenerator.java
  src/main/java/org/sopt/solply_server/domain/place/service/PlaceBookmarkService.java
  src/main/java/org/sopt/solply_server/domain/place/service/PlaceService.java
Labels: FEAT

#99 [FIX] cors 설정, 장소 추천 api 수정 및 컨트롤러 리팩토링
  src/main/java/org/sopt/solply_server/domain/auth/controller/AuthController.java
  src/main/java/org/sopt/solply_server/domain/recommend/service/RecommendService.java
  src/main/java/org/sopt/solply_server/domain/test/service/TestService.java
  src/main/java/org/sopt/solply_server/domain/user/controller/UserController.java
  src/main/java/org/sopt/solply_server/domain/user/controller/UserOnboardingController.java
  src/main/java/org/sopt/solply_server/domain/user/repository/UserInterestTownRepository.java
  src/main/java/org/sopt/solply_server/domain/user/service/SocialUserService.java
  src/main/java/org/sopt/solply_server/domain/user/service/UserInterestTownService.java
  src/main/java/org/sopt/solply_server/domain/user/service/UserOnboardingService.java
  src/main/java/org/sopt/solply_server/domain/user/service/UserService.java
  src/main/java/org/sopt/solply_server/global/config/SecurityConfig.java
  src/main/java/org/sopt/solply_server/global/dto/CustomApiResponse.java
  src/main/java/org/sopt/solply_server/global/handler/GlobalExceptionHandler.java
Labels: BUG

#103 [FEAT] 코스 북마크 필터링 조회 API 구현
  src/main/java/org/sopt/solply_server/domain/course/controller/CourseController.java
  src/main/java/org/sopt/solply_server/domain/course/dto/CourseBookmarkDto.java
  src/main/java/org/sopt/solply_server/domain/course/dto/response/CourseBookmarkListGetResponse.java
  src/main/java/org/sopt/solply_server/domain/course/mapper/CourseMapper.java
  src/main/java/org/sopt/solply_server/domain/course/repository/CourseRepository.java
  src/main/java/org/sopt/solply_server/domain/course/service/CourseService.java
  src/main/java/org/sopt/solply_server/domain/place/service/PlaceService.java
Labels: FEAT

#111 [FIX] 유저 닉네임 중복 체크 과정에서 본인 닉네임은 중복 체크 패싱하도록 수정
  src/main/java/org/sopt/solply_server/domain/user/controller/UserController.java
  src/main/java/org/sopt/solply_server/domain/user/service/UserOnboardingService.java
  src/main/java/org/sopt/solply_server/domain/user/service/UserService.java
  src/main/java/org/sopt/solply_server/domain/user/service/UserValidator.java
Labels: BUG

#112 [CHORE] 이미지 더미데이터 삽입
  src/main/resources/db/migration/V2__insert_initial_data.sql
Labels: CHORE

#116 [FIX] 온보딩 사용자 정보 업데이트 경우에 발생하는 닉네임 중복 검사 버그
  src/main/java/org/sopt/solply_server/domain/user/service/UserService.java
  src/main/java/org/sopt/solply_server/domain/user/service/UserValidator.java
Labels: BUG

#119 chore: hotfix github action 설정, 코스 추천 api uri 수정
  src/main/java/org/sopt/solply_server/domain/recommend/controller/RecommendController.java
Labels: CHORE

#122 [FIX] 이미지 확장자, 플랫폼 반환 언어 변경
  src/main/java/org/sopt/solply_server/domain/place/dto/SnsLinkDto.java
  src/main/java/org/sopt/solply_server/domain/place/entity/SnsPlatform.java
  src/main/resources/db/migration/V2__insert_initial_data.sql
Labels: BUG

#123 [FIX]
  src/main/java/org/sopt/solply_server/domain/course/controller/CourseController.java
  src/main/java/org/sopt/solply_server/domain/course/dto/CourseBookmarkDto.java
  src/main/java/org/sopt/solply_server/domain/course/dto/CourseInfoDto.java
  src/main/java/org/sopt/solply_server/domain/course/dto/response/CourseBookmarkListGetResponse.java
  src/main/java/org/sopt/solply_server/domain/course/repository/CourseRepository.java
  src/main/java/org/sopt/solply_server/domain/course/service/CourseService.java
  src/main/java/org/sopt/solply_server/domain/course/util/CoursePlaceValidator.java
  src/main/java/org/sopt/solply_server/domain/course/util/CourseValidationResult.java
  src/main/resources/db/migration/V2__insert_initial_data.sql
Labels: BUG

#129 [FIX] 복제가 되지 않은 내 코스에 장소를 추가하는 과정에서 발생하는 버그 수정
  .gitignore
  src/main/java/org/sopt/solply_server/domain/course/controller/CourseController.java
  src/main/java/org/sopt/solply_server/domain/course/dto/CourseInfoDto.java
  src/main/java/org/sopt/solply_server/domain/course/dto/CoursePlaceInfo.java
  src/main/java/org/sopt/solply_server/domain/course/dto/CoursePreviewDto.java
  src/main/java/org/sopt/solply_server/domain/course/dto/PlaceInCourseInfo.java
  src/main/java/org/sopt/solply_server/domain/course/dto/response/CourseAddPlaceResponse.java
  src/main/java/org/sopt/solply_server/domain/course/dto/response/CourseUpdateResponse.java
  src/main/java/org/sopt/solply_server/domain/course/dto/response/PlaceAddToCourseResponse.java
  src/main/java/org/sopt/solply_server/domain/course/entity/Course.java
  src/main/java/org/sopt/solply_server/domain/course/entity/CoursePlace.java
  src/main/java/org/sopt/solply_server/domain/course/repository/CoursePlaceRepository.java
  src/main/java/org/sopt/solply_server/domain/course/service/CourseBookmarkService.java
  src/main/java/org/sopt/solply_server/domain/course/service/CoursePlaceService.java
  src/main/java/org/sopt/solply_server/domain/course/service/CourseService.java
  src/main/java/org/sopt/solply_server/domain/course/util/CoursePlaceValidator.java
  src/main/java/org/sopt/solply_server/domain/place/controller/PlaceController.java
  src/main/java/org/sopt/solply_server/domain/place/repository/PlaceRepository.java
  src/main/java/org/sopt/solply_server/domain/place/service/PlaceService.java
  src/main/java/org/sopt/solply_server/global/exception/BusinessException.java
  src/main/java/org/sopt/solply_server/global/exception/ErrorCode.java
  src/main/resources/db/migration/V1__create_initial_tables.sql
Labels: BUG

#140 #139 fix: 기존 코스 삭제 시 코스 이름을 그대로 사용하도록 수정
  src/main/java/org/sopt/solply_server/domain/course/service/CourseService.java
  src/main/java/org/sopt/solply_server/domain/course/util/CourseNameGenerator.java
Labels: 🐞 BUG

#142 [FIX] redis에서도 북마크 활성 여부를 가져오도록 수정
  src/main/java/org/sopt/solply_server/domain/course/service/CourseBookmarkService.java
Labels: 🐞 BUG

#143 readme 수정
  README.md
Labels: 📖 DOCS
