Repository SOLPLY/SOLPLY-SERVER, pull requests merged in 2025-09, with the labels that each got.

#153 [FEAT] pg_trgm 도입, 검색어 기반 장소 조회(3개까지) 기능 구현
  src/main/java/org/sopt/solply_server/domain/place/controller/PlaceController.java
  src/main/java/org/sopt/solply_server/domain/place/dto/PlacePreviewDto.java
  src/main/java/org/sopt/solply_server/domain/place/dto/response/PlaceFilterGetResponse.java
  src/main/java/org/sopt/solply_server/domain/place/dto/response/PlaceSearchResponse.java
  src/main/java/org/sopt/solply_server/domain/place/repository/querydsl/PlaceRepositoryCustom.java
  src/main/java/org/sopt/solply_server/domain/place/repository/querydsl/PlaceRepositoryImpl.java
  src/main/java/org/sopt/solply_server/domain/place/service/PlaceService.java
  src/main/java/org/sopt/solply_server/global/exception/ErrorCode.java
  src/main/resources/db/migration/V4__enable_pg_trgm.sql
Labels: 💭 FEAT

#157 [FEAT] 장소 등록 요청 구현
  src/main/java/org/sopt/solply_server/domain/place/controller/PlaceController.java
  src/main/java/org/sopt/solply_server/domain/place/dto/request/PlaceRequestCreateRequest.java
  src/main/java/org/sopt/solply_server/domain/place/dto/response/PlaceRequestCreateResponse.java
  src/main/java/org/sopt/solply_server/domain/place/entity/PlaceRequest.java
  src/main/java/org/sopt/solply_server/domain/place/entity/PlaceRequestImageInfo.java
  src/main/java/org/sopt/solply_server/domain/place/entity/PlaceRequestTag.java
  src/main/java/org/sopt/solply_server/domain/place/repository/PlaceRequestRepository.java
  src/main/java/org/sopt/solply_server/domain/place/service/PlaceRequestService.java
  src/main/java/org/sopt/solply_server/domain/tag/repository/TagRepository.java
  src/main/resources/db/migration/V3__create_place_request_table.sql
Labels: 💭 FEAT

#158 [FEAT] 잘못된 장소 정보 제보 API 구현
  src/main/java/org/sopt/solply_server/domain/place/controller/PlaceController.java
  src/main/java/org/sopt/solply_server/domain/place/dto/request/PlaceReportCreateRequest.java
  src/main/java/org/sopt/solply_server/domain/place/dto/response/PlaceReportCreateResponse.java
  src/main/java/org/sopt/solply_server/domain/place/entity/PlaceReport.java
  src/main/java/org/sopt/solply_server/domain/place/entity/PlaceReportStatus.java
  src/main/java/org/sopt/solply_server/domain/place/entity/PlaceReportType.java
  src/main/java/org/sopt/solply_server/domain/place/repository/PlaceReportRepository.java
  src/main/java/org/sopt/solply_server/domain/place/service/PlaceReportService.java
  src/main/java/org/sopt/solply_server/domain/place/util/PlaceReportValidator.java
  src/main/java/org/sopt/solply_server/global/exception/ErrorCode.java
  src/main/resources/db/migration/V4__enable_pg_trgm.sql
  src/main/resources/db/migration/V5__create_place_reports_table.sql
Labels: 💭 FEAT

#167 [FEAT] 코스 수정 기능 설명 추가
  src/main/java/org/sopt/solply_server/domain/course/dto/request/CourseUpdateRequest.java
  src/main/java/org/sopt/solply_server/domain/course/dto/response/CourseUpdateResponse.java
  src/main/java/org/sopt/solply_server/domain/course/entity/Course.java
  src/main/java/org/sopt/solply_server/domain/course/service/CourseService.java
Labels: 💭 FEAT

#176 [HOTFIX] flyway로 인해 빌드 실패
  .gitignore
  build.gradle
  src/main/java/org/sopt/solply_server/domain/place/entity/PlaceReport.java
  src/main/java/org/sopt/solply_server/global/cache/RedisCacheService.java
  src/main/java/org/sopt/solply_server/global/config/AwsConfig.java
  src/main/java/org/sopt/solply_server/global/config/RedisConfig.java
  src/main/java/org/sopt/solply_server/global/config/aws/AwsConfig.java
  src/main/java/org/sopt/solply_server/global/config/aws/AwsProperties.java
  src/main/resources/db/migration/V4__enable_pg_trgm.sql
  src/test/java/org/sopt/solply_server/SolplyServerApplicationTests.java
  src/test/resources/application-test.yml
Labels: 🐞 BUG

#170 [FEAT] 북마크 코스 목록 조회 API 업데이트
  src/main/java/org/sopt/solply_server/domain/course/controller/CourseController.java
  src/main/java/org/sopt/solply_server/domain/course/service/CourseService.java
Labels: 💭 FEAT

#180 [CHORE] prometheus, grafana 도입
  .gitignore
  build.gradle
  docker/observability/prometheus.yml
  src/main/java/org/sopt/solply_server/global/config/SecurityConfig.java
Labels: ⚙️ CHORE

#185 [FIX] match_against라는 사용자 정의 함수를 등록, 프로메테우스 세팅 수정
  docker/observability/prometheus.yml
  src/main/java/org/sopt/solply_server/domain/file/controller/FileController.java
  src/main/java/org/sopt/solply_server/domain/file/service/FileService.java
  src/main/java/org/sopt/solply_server/domain/place/dto/PlaceSearchResultDto.java
  src/main/java/org/sopt/solply_server/domain/place/dto/response/PlaceSearchResponse.java
  src/main/java/org/sopt/solply_server/domain/place/repository/querydsl/PlaceRepositoryCustom.java
  src/main/java/org/sopt/solply_server/domain/place/repository/querydsl/PlaceRepositoryImpl.java
  src/main/java/org/sopt/solply_server/domain/place/service/PlaceBookmarkService.java
  src/main/java/org/sopt/solply_server/domain/place/service/PlaceReportImageUpdater.java
  src/main/java/org/sopt/solply_server/domain/place/service/PlaceReportService.java
  src/main/java/org/sopt/solply_server/domain/place/service/PlaceRequestImageUpdater.java
  src/main/java/org/sopt/solply_server/domain/place/service/PlaceRequestService.java
  src/main/java/org/sopt/solply_server/domain/place/service/PlaceService.java
  src/main/java/org/sopt/solply_server/global/config/mysql/MySqlFunctions.java
  src/main/java/org/sopt/solply_server/global/util/s3/PresignedUrlProvider.java
  src/main/resources/META-INF/services/org.hibernate.boot.model.FunctionContributor
Labels: 🐞 BUG

#187 [FEAT] 마이페이지 관련 API 구현
  src/main/java/org/sopt/solply_server/domain/place/dto/PlacePreviewDto.java
  src/main/java/org/sopt/solply_server/domain/place/entity/Place.java
  src/main/java/org/sopt/solply_server/domain/place/repository/PlaceRepository.java
  src/main/java/org/sopt/solply_server/domain/place/service/PlaceService.java
  src/main/java/org/sopt/solply_server/domain/user/controller/UserController.java
  src/main/java/org/sopt/solply_server/domain/user/dto/UserPlacePreviewDto.java
  src/main/java/org/sopt/solply_server/domain/user/dto/WithdrawReasonDto.java
  src/main/java/org/sopt/solply_server/domain/user/dto/request/UserWithdrawRequest.java
  src/main/java/org/sopt/solply_server/domain/user/dto/response/UserProfileGetResponse.java
  src/main/java/org/sopt/solply_server/domain/user/dto/response/UserRequestedPlaceAllGetResponse.java
  src/main/java/org/sopt/solply_server/domain/user/dto/response/UserWithdrawReasonAllGetResponse.java
  src/main/java/org/sopt/solply_server/domain/user/entity/SocialUserInfo.java
  src/main/java/org/sopt/solply_server/domain/user/entity/User.java
  src/main/java/org/sopt/solply_server/domain/user/entity/UserWithdraw.java
  src/main/java/org/sopt/solply_server/domain/user/entity/WithdrawReason.java
  src/main/java/org/sopt/solply_server/domain/user/repository/SocialUserInfoRepository.java
  src/main/java/org/sopt/solply_server/domain/user/repository/UserRepository.java
  src/main/java/org/sopt/solply_server/domain/user/repository/UserWithdrawRepository.java
  src/main/java/org/sopt/solply_server/domain/user/service/UserService.java
  src/main/java/org/sopt/solply_server/domain/user/service/UserWithdrawService.java
  src/main/java/org/sopt/solply_server/domain/user/service/mypage/MyPageFacade.java
  src/main/java/org/sopt/solply_server/global/dto/PagedResponse.java
  src/main/resources/db/migration/V4__add_created_by_to_places.sql
  src/main/resources/db/migration/V5__add_user_withdraw.sql
Labels: 💭 FEAT
